### ISSUE TITLE
The OneDrive link is no longer valid.

### ISSUE THREAD

**Issue by PilgrimGrey1** [GeoffreyChen777/VC#2]
Great work! The OneDrive link for detection is no longer valid. I would like to see the structure of the dict dataset.

**Comment by GeoffreyChen777** [comment]
Hi, thanks. I can open both links in the detection and segmentation folders. Which one is invalid?

**Comment by PilgrimGrey1** [comment]
检测文件夹下的，是不是国内onedrive链接默认重定向了？我一直打不开

**Comment by GeoffreyChen777** [comment]
我没问题哎，估计是国内网的问题吧，找个代理啥的试试。

**Comment by PilgrimGrey1** [comment]
好的好的哥

**Comment by PilgrimGrey1** [comment]
想再请问一下，无标签数据在加载的时候，里面的注释是不会用上的？因此我构造无监督数据dict的时候，注释只要随意给一个形状为[1,5]的张量，能通过filter_empty就行了？

**Comment by GeoffreyChen777** [comment]
那肯定不会用哇，但是如果要计算一些指标，比如pseudo label的准确度啥的你就得用，只是为了可视化训练，如果纯纯为了训练一个模型那就不需要。

**Comment by PilgrimGrey1** [comment]
非常感激！😭因为我实在没时间梳理模型细节了，只能叨扰您了。
